from .base import CustomException


class ValidationError(CustomException):
    pass
